[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"

[env]
CC_aarch64_linux_android = { value = "aarch64-linux-android21-clang", force = true }
CXX_aarch64_linux_android = { value = "aarch64-linux-android21-clang++", force = true }
AR_aarch64_linux_android = { value = "llvm-ar", force = true }