[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]

[env]
CC_aarch64_linux_android = "aarch64-linux-android21-clang"
CXX_aarch64_linux_android = "aarch64-linux-android21-clang++"
AR_aarch64_linux_android = "llvm-ar"
CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER = "aarch64-linux-android21-clang"