[package]
name = "test_android_minimal"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_android_minimal"
path = "src/main.rs"

[dependencies]
# Only basic dependencies without OpenSSL
serde = { version = "1", features = ["derive"] }
serde_json = "1"